# syntax=docker/dockerfile:1.7
# wynd-base 0.1.0-slim. Generated by `wynd base build 0.1.0`. Apache-2.0 contents (spec, runtime).
FROM ghcr.io/astral-sh/uv:0.10.7 AS uv
FROM python:3.12-slim-trixie
COPY --from=uv /uv /uvx /usr/local/bin/
ENV PYTHONUNBUFFERED=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_CACHE_DIR=/var/cache/uv \
    WYND_BASE_VERSION=0.1.0 \
    WYND_BASE_VARIANT=slim \
    WYND_DATA_DIR=/var/lib/wynd \
    WYND_HOME=/var/lib/wynd/home \
    WYND_REGISTRY=env \
    WYND_PLAN=/opt/wynd/process/process.lock.yaml \
    WYND_ENV_MANIFEST=/opt/wynd/process/process.env.yaml \
    WYND_PORT=8080
COPY wheels/ /opt/wynd/wheels/
COPY runtime-requirements.txt /opt/wynd/runtime-requirements.txt
RUN --mount=type=cache,target=/var/cache/uv,sharing=locked \
    uv venv --python /usr/local/bin/python3.12 /opt/wynd/supervisor \
 && uv pip install --python /opt/wynd/supervisor/bin/python --no-deps --find-links /opt/wynd/wheels \
      -r /opt/wynd/runtime-requirements.txt \
 && groupadd --system --gid 10001 wynd && useradd --system --uid 10001 --gid 10001 --home-dir /home/wynd --create-home wynd \
 && mkdir -p /opt/wynd/venvs /opt/wynd/process /var/lib/wynd/home /work \
 && chown -R wynd:wynd /var/lib/wynd /work /home/wynd
WORKDIR /work
USER wynd
EXPOSE 8080
LABEL dev.wynd.base-version="0.1.0" \
      dev.wynd.base-variant="slim" \
      org.opencontainers.image.licenses="Apache-2.0"
ENTRYPOINT ["/opt/wynd/supervisor/bin/wynd-supervisor"]
CMD ["serve"]
