"""`step.lock.yaml` construction and rendering, the step `pyproject.toml`, dependency locking, and the compiler's
provenance model for `StepLock.compiled` (`$DRAFTS/05 §9.1–§9.2`, PLAN §3.6, §7 item 1).

`StepLock.compiled` is an opaque dict to everyone else; only the compiler validates it, with `CompiledInfo`.
`retries = DEFAULT_RETRIES[kind]`; the compiler never writes `provider` (PLAN §15 item 19).
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Literal

from wynd.spec.base import DEFAULT_THINKING, DEFAULT_TIER, SpecModel
from wynd.spec.fragments import EnvFragment, EnvVar, merge_env_vars
from wynd.spec.hashing import normalize_requirement
from wynd.spec.lockfiles import DEFAULT_RETRIES, ShellLock, StepLock, dump_lock
from wynd.spec.workspace import slug

if TYPE_CHECKING:
    from wynd.compiler.astcheck import StaticReport
    from wynd.compiler.tools import ToolCatalog
    from wynd.spec.interface import Interface
    from wynd.spec.lockfiles import StepKind
    from wynd.spec.proto_step import ProtoStep

LOCK_HEADER = (
    "# Generated by wynd compile. This is a review surface: hand edits are kept until the proto-step changes.\n"
    "# Tier-to-model mapping lives in the user registry, never here.\n"
)
EFFECT_ORDER = ("network", "filesystem", "shell")
WYND_DISTS = frozenset({"wynd-spec", "wynd-runtime"})
_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*")


class CompiledSplit(SpecModel):
    role: Literal["deterministic", "agentic"]
    node: str                        # this package's node in process.yaml
    partner: str                     # the other half's package dir name
    partner_node: str
    handled: list[int] = []          # example numbers (deterministic half)
    deferred: list[int] = []


class CompiledInfo(SpecModel):
    session: str
    job: str
    compiler: str                    # "wynd-compiler <version>"
    model: str                       # "<provider>/<tier>" used by the compiler for codegen
    decision: dict                   # {kind, rule, reason}
    inferred_interface: bool = False
    free_text: list[str] = []        # output fields tested for presence only
    guidance: list[str] = []         # clarification answers
    rejected: list[str] = []         # rejected edge-case questions
    split: CompiledSplit | None = None


def compiled_info(lock: StepLock) -> CompiledInfo | None:
    """The lock's `compiled` section as the compiler's model (None for hand-written locks)."""
    return None if lock.compiled is None else CompiledInfo.model_validate(lock.compiled)


# --- pyproject ------------------------------------------------------------------------------------------------------

def project_name(owner: str, package: str) -> str:
    """`<slug(process id or step-root alias)>-<package>`, e.g. `process_supplier_invoice-read_pdf`."""
    return f"{slug(owner)}-{package}"


def render_pyproject(name: str, deps: Sequence[str]) -> str:
    """The step package marker; it mirrors `fragment.deps` (validator W128 compares the names)."""
    return (
        "[project]\n"
        f"name = {json.dumps(name)}\n"
        'version = "0.1.0"\n'
        'requires-python = ">=3.12"\n'
        f"dependencies = [{', '.join(json.dumps(d) for d in deps)}]\n"
        "# wynd-spec and wynd-runtime are not listed: they are installed into every step venv (SPEC §4).\n"
        "\n"
        "[build-system]\n"
        'requires = ["hatchling>=1.27"]\n'
        'build-backend = "hatchling.build"\n'
    )


# --- dependencies ---------------------------------------------------------------------------------------------------

def requirement_name(req: str) -> str:
    match = _NAME.match(req.strip())
    return normalize_requirement(match.group(0)) if match else req.strip()


def merge_deps(proto_deps: Sequence[str], generated: Sequence[str]) -> list[str]:
    """Proto requirements first; a generated requirement is added only when its (PEP 503) name is new, so the proto's
    specifier wins. wynd packages are never listed."""
    out: list[str] = []
    seen: set[str] = set()
    for req in [*proto_deps, *generated]:
        name = requirement_name(req)
        if name in seen or name in WYND_DISTS:
            continue
        seen.add(name)
        out.append(req.strip())
    return out


def locked_deps(deps: Sequence[str], resolve: Callable[[Sequence[str]], list[str]]) -> list[str]:
    """The pinned closure (`CompileDeps.lock_requirements`), sorted, without wynd-spec/runtime; [] without deps."""
    if not deps:
        return []
    return sorted(pin for pin in resolve(list(deps)) if requirement_name(pin) not in WYND_DISTS)


# --- step.lock.yaml -------------------------------------------------------------------------------------------------

def build_step_lock(
    *,
    name: str,
    kind: StepKind,
    entrypoint: str,
    step_id: str,
    proto: ProtoStep | None,
    proto_hash: str | None,
    interface: Interface | None,
    static: StaticReport,
    catalog: ToolCatalog,
    deps: Sequence[str] = (),
    system_packages: Sequence[str] = (),
    requires_glibc: bool = False,
    effects: Sequence[str] = (),
    env_vars: Sequence[tuple[str, str]] = (),
    tier: str | None = None,
    locked: Sequence[str] = (),
    compiled: CompiledInfo | None = None,
) -> StepLock:
    """The lock of a compiled package. `interface` is the one the step venv describes (what the worker verifies at
    import, `interface_hash(interface_from_models(...))`), not the proto fields' schema. Effects are the declared
    ones ∪ tool effects ∪ `network` with MCP ∪ `shell` for a ShellStep; `fragment.vars` merges the proto's vars
    (kept as declared), codegen's `env_vars` and the AST env scan for names the proto does not declare (all
    `step:<id>`), tool env (`tool:<id>/<tool>`) and MCP `auth_env` (`mcp:<server>`, secret)."""
    from wynd.compiler.tools import lock_tools

    agentic = kind == "agentic"
    tools, mcp = lock_tools(static, catalog) if agentic else ([], [])
    wanted = set(effects)
    wanted.update(e for t in tools for e in t.effects)
    if mcp:
        wanted.add("network")
    if kind == "shell":
        wanted.add("shell")
    proto_env = proto.env if proto is not None else EnvFragment()

    step_user = f"step:{step_id}"
    tool_env = {name for t in tools for name in t.env}
    declared = {v.name for v in proto_env.vars}
    variables = [v.model_copy(update={"used_by": [*v.used_by, step_user]}) for v in proto_env.vars]
    variables += [EnvVar(name=n, description=d, used_by=[step_user]) for n, d in env_vars if n not in declared]
    variables += [EnvVar(name=n, used_by=[step_user]) for n in sorted(static.env_vars - tool_env - declared)]
    variables += [EnvVar(name=n, used_by=[f"tool:{step_id}/{t.name}"]) for t in tools for n in t.env]
    for snap in mcp:
        entry = catalog.server(snap.server).entry
        variables += [EnvVar(name=n, secret=True, used_by=[f"mcp:{snap.server}"]) for n in entry.auth_env]
    fragment = EnvFragment(
        deps=merge_deps(proto_env.deps, deps),
        system=sorted({*proto_env.system, *system_packages}),
        requires="glibc" if proto_env.requires == "glibc" or requires_glibc else None,
        vars=merge_env_vars(variables),
        groups=dict(proto_env.groups),
    )
    shell = None
    if kind == "shell":
        codes = proto.exit_codes if proto is not None and proto.exit_codes else None
        shell = ShellLock(exit_codes=codes) if codes else ShellLock()
    return StepLock(
        name=name,
        kind=kind,
        entrypoint=entrypoint,
        proto_hash=proto_hash,
        tier=(tier or DEFAULT_TIER) if agentic else None,
        thinking=DEFAULT_THINKING if agentic else None,
        retries=DEFAULT_RETRIES[kind].model_copy(),
        effects=[e for e in EFFECT_ORDER if e in wanted],
        tools=tools,
        mcp=mcp,
        context=list(static.context) if agentic else [],
        shell=shell,
        fragment=fragment,
        locked_deps=list(locked),
        interface=interface,
        compiled=compiled.model_dump(mode="json") if compiled is not None else None,
    )


def render_step_lock(lock: StepLock) -> str:
    return LOCK_HEADER + dump_lock(lock)
