"""Generated step test files, one `test_example_<n>` per example (`$DRAFTS/05 §9.3.1`, PLAN §3.20). There is no
generated process test file (PLAN §7 item 2): process examples run directly from `process.yaml`.

The output depends only on its arguments (the same examples give the same bytes) and is generated before any code
exists. Rules: `n` is the 1-based example position; a description becomes the docstring; values are emitted with
`pprint.pformat(width=100)`; relative `path` values become `str(BASE / "<value>")` (`BASE` = the process dir for
process-local steps, the package dir for step-root steps); a `{tmp}` value wraps the example's inputs and expected
outputs in `sub_tmp(…, tmp_path)` and moves the run workspace to `tmp_path / "ws"`; free-text output fields are
checked with `present=[…]`; `exit: error` examples and the deferred examples of a split's deterministic half expect
the `error` exit.
"""

from __future__ import annotations

import pprint
from collections.abc import Mapping, Sequence
from pathlib import PurePosixPath
from typing import Any

from wynd.spec.base import RESERVED_EXIT
from wynd.spec.proto_step import Example
from wynd.spec.typelang import TList, TObject, TScalar, TypeNode

TMP = "{tmp}"
HEADER = ("# One test per example. Change the proto-step's examples and recompile instead of editing this file.")


class _Expr:
    """Python source emitted as-is inside a pformat'ed value."""

    def __init__(self, text: str):
        self.text = text

    def __repr__(self) -> str:
        return self.text


def step_tests(
    class_name: str,
    examples: Sequence[Example],
    inputs: Mapping[str, TypeNode],
    *,
    source: str,
    proto_hash: str | None = None,
    step_root: bool = False,
    free_text: Sequence[str] = (),
    deferred: Sequence[int] = (),
    partner: str | None = None,
) -> str:
    """The `test_<package>.py` source. `examples` are canonical (`schemas.canonical`); `source` names the proto file
    in the header (e.g. `proto/extract_invoice_fields.yaml`); `deferred` are example numbers that a split's
    deterministic half must hand off (`partner` is the agentic half's package)."""
    bodies = [_test(n, example, class_name, inputs, free_text, n in deferred, partner)
              for n, example in enumerate(examples, 1)]
    uses_base = any("BASE /" in body for body in bodies)
    uses_tmp = any("sub_tmp(" in body for body in bodies)
    hashed = f" ({proto_hash})" if proto_hash else ""
    lines = [
        f"# Generated by wynd compile from {source}{hashed}.",
        HEADER,
        "from pathlib import Path",
        "",
        f"from wynd.runtime.testing import expect, load_step, run_step{', sub_tmp' if uses_tmp else ''}",
        "",
        f"{class_name} = load_step(Path(__file__).parent)",
    ]
    if uses_base:
        depth, where = (0, "the package directory") if step_root else (2, "the process directory")
        lines.append(f"BASE = Path(__file__).resolve().parents[{depth}]   # relative example paths resolve against "
                     f"{where}")
    return "\n".join(lines) + "\n" + "".join("\n\n" + body for body in bodies)


def _test(n: int, example: Example, class_name: str, inputs: Mapping[str, TypeNode], free_text: Sequence[str],
          deferred: bool, partner: str | None) -> str:
    values = {k: _paths(inputs.get(k), v) for k, v in example.inputs.items()}
    tmp = _has_tmp(example.inputs) or _has_tmp(example.outputs)
    lines = [f"def test_example_{n}(tmp_path):"]
    if example.description:
        lines.append(f"    {_docstring(example.description)}")
    workspace = 'tmp_path / "ws"' if tmp else "tmp_path"
    if tmp:
        lines.append(f"    inputs = sub_tmp({_fmt(values, 21)}, tmp_path)")
    one = f"    result = run_step({class_name}, {'inputs' if tmp else _fmt(values, 0)}, workspace={workspace})"
    if len(one) <= 120 and "\n" not in one:
        lines.append(one)
    else:
        arg = "inputs" if tmp else _fmt(values, 8)
        lines += ["    result = run_step(", f"        {class_name},", f"        {arg},",
                  f"        workspace={workspace},", "    )"]
    if deferred:
        lines.append(f"    # handled by {partner} (split): this step must hand off, not guess")
    lines += _expect(example, free_text, deferred, tmp)
    return "\n".join(lines) + "\n"


def _expect(example: Example, free_text: Sequence[str], deferred: bool, tmp: bool) -> list[str]:
    if deferred or example.exit == RESERVED_EXIT:
        return ['    expect(result, exit="error")']
    present = [f for f in free_text if f in example.outputs]
    outputs = {k: v for k, v in example.outputs.items() if k not in present}
    wrap = tmp and _has_tmp(outputs)

    def args(indent: int) -> list[str]:
        out = [f'exit="{example.exit}"']
        if outputs:
            out.append(f"outputs=sub_tmp({_fmt(outputs, indent + 16)}, tmp_path)" if wrap
                       else f"outputs={_fmt(outputs, indent + 8)}")
        if present:
            out.append(f"present={present!r}")
        return out

    one = f"    expect(result, {', '.join(args(0))})"
    if len(one) <= 120 and "\n" not in one:
        return [one]
    return ["    expect(", "        result,", *[f"        {arg}," for arg in args(8)], "    )"]


def _fmt(value: Any, indent: int) -> str:
    """pformat with continuation lines indented to sit under the opening bracket's line."""
    text = pprint.pformat(value, width=100, sort_dicts=False)
    return text.replace("\n", "\n" + " " * indent)


def _docstring(text: str) -> str:
    body = " ".join(text.split()).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if body.endswith('"'):
        body += " "
    return f'"""{body}"""'


def _has_tmp(value: Any) -> bool:
    match value:
        case str():
            return value.startswith(TMP)
        case Mapping():
            return any(_has_tmp(v) for v in value.values())
        case list():
            return any(_has_tmp(v) for v in value)
    return False


def _paths(node: TypeNode | None, value: Any) -> Any:
    """Relative `path` values (not `{tmp}`, not absolute) become `str(BASE / "<value>")` expressions."""
    match node:
        case TScalar(name="path") if isinstance(value, str) and _relative(value):
            return _Expr(f"str(BASE / {value!r})")
        case TList() if isinstance(value, list):
            return [_paths(node.item, item) for item in value]
        case TObject() if isinstance(value, Mapping):
            fields = dict(node.fields)
            return {k: _paths(fields.get(k), v) for k, v in value.items()}
    return value


def _relative(value: str) -> bool:
    return bool(value) and not value.startswith(TMP) and not PurePosixPath(value).is_absolute() and "~" != value[:1]
